// Code generated by protoc-gen-go. DO NOT EDIT.
// source: calculator/calculator.proto

package calculator

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Operation int32

const (
	Operation_SUM Operation = 0
)

var Operation_name = map[int32]string{
	0: "SUM",
}

var Operation_value = map[string]int32{
	"SUM": 0,
}

func (x Operation) String() string {
	return proto.EnumName(Operation_name, int32(x))
}

func (Operation) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_efa30b76d83302dd, []int{0}
}

type Equation struct {
	X                    int32     `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32     `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Operation            Operation `protobuf:"varint,3,opt,name=operation,proto3,enum=calculator.Operation" json:"operation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Equation) Reset()         { *m = Equation{} }
func (m *Equation) String() string { return proto.CompactTextString(m) }
func (*Equation) ProtoMessage()    {}
func (*Equation) Descriptor() ([]byte, []int) {
	return fileDescriptor_efa30b76d83302dd, []int{0}
}

func (m *Equation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Equation.Unmarshal(m, b)
}
func (m *Equation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Equation.Marshal(b, m, deterministic)
}
func (m *Equation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Equation.Merge(m, src)
}
func (m *Equation) XXX_Size() int {
	return xxx_messageInfo_Equation.Size(m)
}
func (m *Equation) XXX_DiscardUnknown() {
	xxx_messageInfo_Equation.DiscardUnknown(m)
}

var xxx_messageInfo_Equation proto.InternalMessageInfo

func (m *Equation) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Equation) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Equation) GetOperation() Operation {
	if m != nil {
		return m.Operation
	}
	return Operation_SUM
}

type Result struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_efa30b76d83302dd, []int{1}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterEnum("calculator.Operation", Operation_name, Operation_value)
	proto.RegisterType((*Equation)(nil), "calculator.Equation")
	proto.RegisterType((*Result)(nil), "calculator.Result")
}

func init() { proto.RegisterFile("calculator/calculator.proto", fileDescriptor_efa30b76d83302dd) }

var fileDescriptor_efa30b76d83302dd = []byte{
	// 184 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4e, 0x4e, 0xcc, 0x49,
	0x2e, 0xcd, 0x49, 0x2c, 0xc9, 0x2f, 0xd2, 0x47, 0x30, 0xf5, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85,
	0xb8, 0x10, 0x22, 0x4a, 0xd1, 0x5c, 0x1c, 0xae, 0x85, 0xa5, 0x89, 0x25, 0x99, 0xf9, 0x79, 0x42,
	0x3c, 0x5c, 0x8c, 0x15, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xac, 0x41, 0x8c, 0x15, 0x20, 0x5e, 0xa5,
	0x04, 0x13, 0x84, 0x57, 0x29, 0x64, 0xcc, 0xc5, 0x99, 0x5f, 0x90, 0x5a, 0x04, 0x56, 0x28, 0xc1,
	0xac, 0xc0, 0xa8, 0xc1, 0x67, 0x24, 0xaa, 0x87, 0x64, 0xb2, 0x3f, 0x4c, 0x32, 0x08, 0xa1, 0x4e,
	0x49, 0x81, 0x8b, 0x2d, 0x28, 0xb5, 0xb8, 0x34, 0xa7, 0x44, 0x48, 0x8c, 0x8b, 0xad, 0x08, 0xcc,
	0x82, 0x9a, 0x0f, 0xe5, 0x69, 0x89, 0x70, 0x71, 0xc2, 0x75, 0x0a, 0xb1, 0x73, 0x31, 0x07, 0x87,
	0xfa, 0x0a, 0x30, 0x18, 0xb9, 0x72, 0x71, 0x39, 0xc3, 0x8d, 0x16, 0x32, 0xe7, 0xe2, 0x84, 0xf1,
	0x52, 0x85, 0x44, 0x90, 0x2d, 0x85, 0xb9, 0x5c, 0x4a, 0x08, 0x59, 0x14, 0x62, 0xa5, 0x12, 0x83,
	0x13, 0x4f, 0x14, 0x92, 0x4f, 0x93, 0xd8, 0xc0, 0x9e, 0x37, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff,
	0x87, 0x8c, 0xc2, 0xa8, 0x1b, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CalculatorClient is the client API for Calculator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CalculatorClient interface {
	Calculate(ctx context.Context, in *Equation, opts ...grpc.CallOption) (*Result, error)
}

type calculatorClient struct {
	cc *grpc.ClientConn
}

func NewCalculatorClient(cc *grpc.ClientConn) CalculatorClient {
	return &calculatorClient{cc}
}

func (c *calculatorClient) Calculate(ctx context.Context, in *Equation, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/calculator.Calculator/Calculate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CalculatorServer is the server API for Calculator service.
type CalculatorServer interface {
	Calculate(context.Context, *Equation) (*Result, error)
}

// UnimplementedCalculatorServer can be embedded to have forward compatible implementations.
type UnimplementedCalculatorServer struct {
}

func (*UnimplementedCalculatorServer) Calculate(ctx context.Context, req *Equation) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Calculate not implemented")
}

func RegisterCalculatorServer(s *grpc.Server, srv CalculatorServer) {
	s.RegisterService(&_Calculator_serviceDesc, srv)
}

func _Calculator_Calculate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Equation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServer).Calculate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calculator.Calculator/Calculate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServer).Calculate(ctx, req.(*Equation))
	}
	return interceptor(ctx, in, info, handler)
}

var _Calculator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "calculator.Calculator",
	HandlerType: (*CalculatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Calculate",
			Handler:    _Calculator_Calculate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "calculator/calculator.proto",
}
